name: Validate and Test Build

on: [pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: validation
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install black
      - name: Run black
        run: |
          black --check --diff aws_cdk_config

  validate-dependencies:
    runs-on: ubuntu-latest
    environment: validation
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install poetry
      - name: Check lock file
        run: poetry check --lock

  pytest:
    needs: validate-dependencies
    runs-on: ubuntu-latest
    environment: validation
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Pytest
        run: |
          poetry run pytest

  test-build:
    runs-on: ubuntu-latest
    environment: validation
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install poetry
      - name: Build
        run: poetry build
      - name: Install
        run: pip install dist/*.tar.gz